### ISSUE TITLE
Exception in __del__ for unclosed loop

### ISSUE THREAD

**Issue by fancidev** [fancidev/asyncslot#1]
test_del.py in commit [ff64eaf](https://github.com/fancidev/asyncslot/commit/ff64eaf918e28b6477c529275527fe6ede210dca) raises the following exception when program exits:

```
/Users/fancidev/asyncslot/.venv/bin/python /Users/fancidev/asyncslot/test_del.py 
Hi
Bye
sys:1: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:681: ResourceWarning: unclosed event loop <CustomEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fe3903f44c0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 277, in _remove_reader
    key = self._selector.get_key(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1

Process finished with exit code 0
```

The exception (and ResourceWarning) varies when certain (attribute or method) members of `CustomSelector` are commented out; the behavior looks random.

No exception is thrown if `from PySide6 import QtCore` is commented out, or if `PySide6` is replaced with `PyQt6`.

The ResourceWarnings suggest an (unexpected) reference cycle might be introduced when `PySide6.QtCore` is imported.

A (proper) workaround is to close the loop after use.

**Comment by fancidev** [comment]
Added `tests/dep_test_del.py` in commit [22445a2](https://github.com/fancidev/asyncslot/commit/22445a2125a0052a59adbc52c0c0885e73f8efc5) to reproduce the error under PyQt6, PySide2 and PySide6. (PyQt5 looks ok.) I'm unable to reproduce the error with simple code that uses `asyncslot`; plus the standard usage of `asyncslot` always closes the event loop. So I'm closing the issue for now until we find a recurrence in the future.
